language: cpp
sudo: false

compiler:
 - clang
 - gcc

env:
  global:
   - secure: "jA29KvTCTR7q4BMzPPUBGazjJwrIWa7k4fo5ZSMlyxh2NbztZTKQYwodgDcXBoptCd1KJ9H3FXwBnNdMNVnTkvoPL9uWnN4K/3D1D20FCag1kmlBwnaVqVei5cRiZ9TOMuaxhjkdg8pcrQLTlXEEdMZf6A2OW0VgoBGDVSX9nYc="

branches:
  except:
    - ppu_recompiler

git:
  submodules: false

before_install:
 - if [ "$CXX" = "g++" ]; then
     export CXX="g++-4.9" CC="gcc-4.9";
     export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01';
   else
     export CXX="clang++-3.6" CC="clang-3.6";
   fi;

before_script:
 - git submodule update --init asmjit ffmpeg llvm
 - mkdir build
 - cd build
 - cmake ..

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kubuntu-backports
    packages:
    - cmake
    - g++-4.9
    - libwxgtk3.0-dev
    - libopenal-dev 
    - freeglut3-dev 
    - libglew-dev 
    - libc6-dev
    - llvm-3.6 
    - llvm-3.6-dev 
    - clang-3.6 
    - libstdc++-4.8-dev
    - lib32stdc++6
  coverity_scan:
    project:
      name: "DHrpcs3/rpcs3"
      description: "PS3 emulator/debugger"
    notification_email: raul.tambre@gmail.com
    build_command_prepend: ""
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

# These modifys are from https://github.com/devernay/cminpack/blob/master/.travis.yml
# It passed but when coverall it failed.
script:
# Add a command to show all the variables now. maybe only useful for debugging travis.
 - echo "--Shell Export Lists START--" ; export -p; echo "--Shell Export Lists STOP--";
# And to ensure the versions of toolchain
 - echo "--CXX version?"; "$CXX" --version; echo "--CXX version confirmed";
# From https://github.com/devernay/cminpack/blob/master/.travis.yml: that is $COVERITY_SCAN_BRANCH not ${COVERITY_SCAN_BRANCH}
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j 4; fi
after_success:
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then coveralls --extension .c --extension .cpp --extension .h; fi
